/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClientRouteImport } from './routes/client'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeveloperIndexRouteImport } from './routes/developer.index'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as TalentUserIdRouteImport } from './routes/talent.$userId'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as DeveloperWalletRouteImport } from './routes/developer.wallet'
import { Route as DeveloperSettingsRouteImport } from './routes/developer.settings'
import { Route as DeveloperProposalsRouteImport } from './routes/developer.proposals'
import { Route as DeveloperProfileRouteImport } from './routes/developer.profile'
import { Route as DeveloperPaymentMethodsRouteImport } from './routes/developer.payment-methods'
import { Route as DeveloperMessagesRouteImport } from './routes/developer.messages'
import { Route as DeveloperJobsForYouRouteImport } from './routes/developer.jobs-for-you'
import { Route as DeveloperJobsRouteImport } from './routes/developer.jobs'
import { Route as DeveloperContractsRouteImport } from './routes/developer.contracts'
import { Route as DebugImpersonateRouteImport } from './routes/debug/impersonate'
import { Route as DebugAuthStateRouteImport } from './routes/debug/auth-state'
import { Route as ClientSettingsRouteImport } from './routes/client.settings'
import { Route as ClientProposalsRouteImport } from './routes/client.proposals'
import { Route as ClientPostJobRouteImport } from './routes/client.post-job'
import { Route as ClientPaymentsRouteImport } from './routes/client.payments'
import { Route as ClientMessagesRouteImport } from './routes/client.messages'
import { Route as ClientJobsRouteImport } from './routes/client.jobs'
import { Route as ClientDevelopersRouteImport } from './routes/client.developers'
import { Route as ClientContractsRouteImport } from './routes/client.contracts'
import { Route as ClientProjectsJobIdRouteImport } from './routes/client.projects.$jobId'
import { Route as ClientDisputesNewRouteImport } from './routes/client.disputes.new'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperIndexRoute = DeveloperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeveloperRoute,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const TalentUserIdRoute = TalentUserIdRouteImport.update({
  id: '/talent/$userId',
  path: '/talent/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => JobsRoute,
} as any)
const DeveloperWalletRoute = DeveloperWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DeveloperRoute,
} as any)
const DeveloperSettingsRoute = DeveloperSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DeveloperRoute,
} as any)
const DeveloperProposalsRoute = DeveloperProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => DeveloperRoute,
} as any)
const DeveloperProfileRoute = DeveloperProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DeveloperRoute,
} as any)
const DeveloperPaymentMethodsRoute = DeveloperPaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => DeveloperRoute,
} as any)
const DeveloperMessagesRoute = DeveloperMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DeveloperRoute,
} as any)
const DeveloperJobsForYouRoute = DeveloperJobsForYouRouteImport.update({
  id: '/jobs-for-you',
  path: '/jobs-for-you',
  getParentRoute: () => DeveloperRoute,
} as any)
const DeveloperJobsRoute = DeveloperJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DeveloperRoute,
} as any)
const DeveloperContractsRoute = DeveloperContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => DeveloperRoute,
} as any)
const DebugImpersonateRoute = DebugImpersonateRouteImport.update({
  id: '/debug/impersonate',
  path: '/debug/impersonate',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugAuthStateRoute = DebugAuthStateRouteImport.update({
  id: '/debug/auth-state',
  path: '/debug/auth-state',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientSettingsRoute = ClientSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ClientRoute,
} as any)
const ClientProposalsRoute = ClientProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => ClientRoute,
} as any)
const ClientPostJobRoute = ClientPostJobRouteImport.update({
  id: '/post-job',
  path: '/post-job',
  getParentRoute: () => ClientRoute,
} as any)
const ClientPaymentsRoute = ClientPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ClientRoute,
} as any)
const ClientMessagesRoute = ClientMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ClientRoute,
} as any)
const ClientJobsRoute = ClientJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => ClientRoute,
} as any)
const ClientDevelopersRoute = ClientDevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => ClientRoute,
} as any)
const ClientContractsRoute = ClientContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => ClientRoute,
} as any)
const ClientProjectsJobIdRoute = ClientProjectsJobIdRouteImport.update({
  id: '/projects/$jobId',
  path: '/projects/$jobId',
  getParentRoute: () => ClientRoute,
} as any)
const ClientDisputesNewRoute = ClientDisputesNewRouteImport.update({
  id: '/disputes/new',
  path: '/disputes/new',
  getParentRoute: () => ClientRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client': typeof ClientRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/developer': typeof DeveloperRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/wallet': typeof WalletRoute
  '/client/contracts': typeof ClientContractsRoute
  '/client/developers': typeof ClientDevelopersRoute
  '/client/jobs': typeof ClientJobsRoute
  '/client/messages': typeof ClientMessagesRoute
  '/client/payments': typeof ClientPaymentsRoute
  '/client/post-job': typeof ClientPostJobRoute
  '/client/proposals': typeof ClientProposalsRoute
  '/client/settings': typeof ClientSettingsRoute
  '/debug/auth-state': typeof DebugAuthStateRoute
  '/debug/impersonate': typeof DebugImpersonateRoute
  '/developer/contracts': typeof DeveloperContractsRoute
  '/developer/jobs': typeof DeveloperJobsRoute
  '/developer/jobs-for-you': typeof DeveloperJobsForYouRoute
  '/developer/messages': typeof DeveloperMessagesRoute
  '/developer/payment-methods': typeof DeveloperPaymentMethodsRoute
  '/developer/profile': typeof DeveloperProfileRoute
  '/developer/proposals': typeof DeveloperProposalsRoute
  '/developer/settings': typeof DeveloperSettingsRoute
  '/developer/wallet': typeof DeveloperWalletRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/talent/$userId': typeof TalentUserIdRoute
  '/client/': typeof ClientIndexRoute
  '/developer/': typeof DeveloperIndexRoute
  '/client/disputes/new': typeof ClientDisputesNewRoute
  '/client/projects/$jobId': typeof ClientProjectsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/wallet': typeof WalletRoute
  '/client/contracts': typeof ClientContractsRoute
  '/client/developers': typeof ClientDevelopersRoute
  '/client/jobs': typeof ClientJobsRoute
  '/client/messages': typeof ClientMessagesRoute
  '/client/payments': typeof ClientPaymentsRoute
  '/client/post-job': typeof ClientPostJobRoute
  '/client/proposals': typeof ClientProposalsRoute
  '/client/settings': typeof ClientSettingsRoute
  '/debug/auth-state': typeof DebugAuthStateRoute
  '/debug/impersonate': typeof DebugImpersonateRoute
  '/developer/contracts': typeof DeveloperContractsRoute
  '/developer/jobs': typeof DeveloperJobsRoute
  '/developer/jobs-for-you': typeof DeveloperJobsForYouRoute
  '/developer/messages': typeof DeveloperMessagesRoute
  '/developer/payment-methods': typeof DeveloperPaymentMethodsRoute
  '/developer/profile': typeof DeveloperProfileRoute
  '/developer/proposals': typeof DeveloperProposalsRoute
  '/developer/settings': typeof DeveloperSettingsRoute
  '/developer/wallet': typeof DeveloperWalletRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/talent/$userId': typeof TalentUserIdRoute
  '/client': typeof ClientIndexRoute
  '/developer': typeof DeveloperIndexRoute
  '/client/disputes/new': typeof ClientDisputesNewRoute
  '/client/projects/$jobId': typeof ClientProjectsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/client': typeof ClientRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/developer': typeof DeveloperRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/wallet': typeof WalletRoute
  '/client/contracts': typeof ClientContractsRoute
  '/client/developers': typeof ClientDevelopersRoute
  '/client/jobs': typeof ClientJobsRoute
  '/client/messages': typeof ClientMessagesRoute
  '/client/payments': typeof ClientPaymentsRoute
  '/client/post-job': typeof ClientPostJobRoute
  '/client/proposals': typeof ClientProposalsRoute
  '/client/settings': typeof ClientSettingsRoute
  '/debug/auth-state': typeof DebugAuthStateRoute
  '/debug/impersonate': typeof DebugImpersonateRoute
  '/developer/contracts': typeof DeveloperContractsRoute
  '/developer/jobs': typeof DeveloperJobsRoute
  '/developer/jobs-for-you': typeof DeveloperJobsForYouRoute
  '/developer/messages': typeof DeveloperMessagesRoute
  '/developer/payment-methods': typeof DeveloperPaymentMethodsRoute
  '/developer/profile': typeof DeveloperProfileRoute
  '/developer/proposals': typeof DeveloperProposalsRoute
  '/developer/settings': typeof DeveloperSettingsRoute
  '/developer/wallet': typeof DeveloperWalletRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/talent/$userId': typeof TalentUserIdRoute
  '/client/': typeof ClientIndexRoute
  '/developer/': typeof DeveloperIndexRoute
  '/client/disputes/new': typeof ClientDisputesNewRoute
  '/client/projects/$jobId': typeof ClientProjectsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client'
    | '/dashboard'
    | '/developer'
    | '/jobs'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/signup'
    | '/wallet'
    | '/client/contracts'
    | '/client/developers'
    | '/client/jobs'
    | '/client/messages'
    | '/client/payments'
    | '/client/post-job'
    | '/client/proposals'
    | '/client/settings'
    | '/debug/auth-state'
    | '/debug/impersonate'
    | '/developer/contracts'
    | '/developer/jobs'
    | '/developer/jobs-for-you'
    | '/developer/messages'
    | '/developer/payment-methods'
    | '/developer/profile'
    | '/developer/proposals'
    | '/developer/settings'
    | '/developer/wallet'
    | '/jobs/$jobId'
    | '/talent/$userId'
    | '/client/'
    | '/developer/'
    | '/client/disputes/new'
    | '/client/projects/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/jobs'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/signup'
    | '/wallet'
    | '/client/contracts'
    | '/client/developers'
    | '/client/jobs'
    | '/client/messages'
    | '/client/payments'
    | '/client/post-job'
    | '/client/proposals'
    | '/client/settings'
    | '/debug/auth-state'
    | '/debug/impersonate'
    | '/developer/contracts'
    | '/developer/jobs'
    | '/developer/jobs-for-you'
    | '/developer/messages'
    | '/developer/payment-methods'
    | '/developer/profile'
    | '/developer/proposals'
    | '/developer/settings'
    | '/developer/wallet'
    | '/jobs/$jobId'
    | '/talent/$userId'
    | '/client'
    | '/developer'
    | '/client/disputes/new'
    | '/client/projects/$jobId'
  id:
    | '__root__'
    | '/'
    | '/client'
    | '/dashboard'
    | '/developer'
    | '/jobs'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/signup'
    | '/wallet'
    | '/client/contracts'
    | '/client/developers'
    | '/client/jobs'
    | '/client/messages'
    | '/client/payments'
    | '/client/post-job'
    | '/client/proposals'
    | '/client/settings'
    | '/debug/auth-state'
    | '/debug/impersonate'
    | '/developer/contracts'
    | '/developer/jobs'
    | '/developer/jobs-for-you'
    | '/developer/messages'
    | '/developer/payment-methods'
    | '/developer/profile'
    | '/developer/proposals'
    | '/developer/settings'
    | '/developer/wallet'
    | '/jobs/$jobId'
    | '/talent/$userId'
    | '/client/'
    | '/developer/'
    | '/client/disputes/new'
    | '/client/projects/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientRoute: typeof ClientRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DeveloperRoute: typeof DeveloperRouteWithChildren
  JobsRoute: typeof JobsRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  WalletRoute: typeof WalletRoute
  DebugAuthStateRoute: typeof DebugAuthStateRoute
  DebugImpersonateRoute: typeof DebugImpersonateRoute
  TalentUserIdRoute: typeof TalentUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/': {
      id: '/developer/'
      path: '/'
      fullPath: '/developer/'
      preLoaderRoute: typeof DeveloperIndexRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/talent/$userId': {
      id: '/talent/$userId'
      path: '/talent/$userId'
      fullPath: '/talent/$userId'
      preLoaderRoute: typeof TalentUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/developer/wallet': {
      id: '/developer/wallet'
      path: '/wallet'
      fullPath: '/developer/wallet'
      preLoaderRoute: typeof DeveloperWalletRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/developer/settings': {
      id: '/developer/settings'
      path: '/settings'
      fullPath: '/developer/settings'
      preLoaderRoute: typeof DeveloperSettingsRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/developer/proposals': {
      id: '/developer/proposals'
      path: '/proposals'
      fullPath: '/developer/proposals'
      preLoaderRoute: typeof DeveloperProposalsRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/developer/profile': {
      id: '/developer/profile'
      path: '/profile'
      fullPath: '/developer/profile'
      preLoaderRoute: typeof DeveloperProfileRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/developer/payment-methods': {
      id: '/developer/payment-methods'
      path: '/payment-methods'
      fullPath: '/developer/payment-methods'
      preLoaderRoute: typeof DeveloperPaymentMethodsRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/developer/messages': {
      id: '/developer/messages'
      path: '/messages'
      fullPath: '/developer/messages'
      preLoaderRoute: typeof DeveloperMessagesRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/developer/jobs-for-you': {
      id: '/developer/jobs-for-you'
      path: '/jobs-for-you'
      fullPath: '/developer/jobs-for-you'
      preLoaderRoute: typeof DeveloperJobsForYouRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/developer/jobs': {
      id: '/developer/jobs'
      path: '/jobs'
      fullPath: '/developer/jobs'
      preLoaderRoute: typeof DeveloperJobsRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/developer/contracts': {
      id: '/developer/contracts'
      path: '/contracts'
      fullPath: '/developer/contracts'
      preLoaderRoute: typeof DeveloperContractsRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/debug/impersonate': {
      id: '/debug/impersonate'
      path: '/debug/impersonate'
      fullPath: '/debug/impersonate'
      preLoaderRoute: typeof DebugImpersonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/auth-state': {
      id: '/debug/auth-state'
      path: '/debug/auth-state'
      fullPath: '/debug/auth-state'
      preLoaderRoute: typeof DebugAuthStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/settings': {
      id: '/client/settings'
      path: '/settings'
      fullPath: '/client/settings'
      preLoaderRoute: typeof ClientSettingsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/proposals': {
      id: '/client/proposals'
      path: '/proposals'
      fullPath: '/client/proposals'
      preLoaderRoute: typeof ClientProposalsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/post-job': {
      id: '/client/post-job'
      path: '/post-job'
      fullPath: '/client/post-job'
      preLoaderRoute: typeof ClientPostJobRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/payments': {
      id: '/client/payments'
      path: '/payments'
      fullPath: '/client/payments'
      preLoaderRoute: typeof ClientPaymentsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/messages': {
      id: '/client/messages'
      path: '/messages'
      fullPath: '/client/messages'
      preLoaderRoute: typeof ClientMessagesRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/jobs': {
      id: '/client/jobs'
      path: '/jobs'
      fullPath: '/client/jobs'
      preLoaderRoute: typeof ClientJobsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/developers': {
      id: '/client/developers'
      path: '/developers'
      fullPath: '/client/developers'
      preLoaderRoute: typeof ClientDevelopersRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/contracts': {
      id: '/client/contracts'
      path: '/contracts'
      fullPath: '/client/contracts'
      preLoaderRoute: typeof ClientContractsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/projects/$jobId': {
      id: '/client/projects/$jobId'
      path: '/projects/$jobId'
      fullPath: '/client/projects/$jobId'
      preLoaderRoute: typeof ClientProjectsJobIdRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/disputes/new': {
      id: '/client/disputes/new'
      path: '/disputes/new'
      fullPath: '/client/disputes/new'
      preLoaderRoute: typeof ClientDisputesNewRouteImport
      parentRoute: typeof ClientRoute
    }
  }
}

interface ClientRouteChildren {
  ClientContractsRoute: typeof ClientContractsRoute
  ClientDevelopersRoute: typeof ClientDevelopersRoute
  ClientJobsRoute: typeof ClientJobsRoute
  ClientMessagesRoute: typeof ClientMessagesRoute
  ClientPaymentsRoute: typeof ClientPaymentsRoute
  ClientPostJobRoute: typeof ClientPostJobRoute
  ClientProposalsRoute: typeof ClientProposalsRoute
  ClientSettingsRoute: typeof ClientSettingsRoute
  ClientIndexRoute: typeof ClientIndexRoute
  ClientDisputesNewRoute: typeof ClientDisputesNewRoute
  ClientProjectsJobIdRoute: typeof ClientProjectsJobIdRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientContractsRoute: ClientContractsRoute,
  ClientDevelopersRoute: ClientDevelopersRoute,
  ClientJobsRoute: ClientJobsRoute,
  ClientMessagesRoute: ClientMessagesRoute,
  ClientPaymentsRoute: ClientPaymentsRoute,
  ClientPostJobRoute: ClientPostJobRoute,
  ClientProposalsRoute: ClientProposalsRoute,
  ClientSettingsRoute: ClientSettingsRoute,
  ClientIndexRoute: ClientIndexRoute,
  ClientDisputesNewRoute: ClientDisputesNewRoute,
  ClientProjectsJobIdRoute: ClientProjectsJobIdRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface DeveloperRouteChildren {
  DeveloperContractsRoute: typeof DeveloperContractsRoute
  DeveloperJobsRoute: typeof DeveloperJobsRoute
  DeveloperJobsForYouRoute: typeof DeveloperJobsForYouRoute
  DeveloperMessagesRoute: typeof DeveloperMessagesRoute
  DeveloperPaymentMethodsRoute: typeof DeveloperPaymentMethodsRoute
  DeveloperProfileRoute: typeof DeveloperProfileRoute
  DeveloperProposalsRoute: typeof DeveloperProposalsRoute
  DeveloperSettingsRoute: typeof DeveloperSettingsRoute
  DeveloperWalletRoute: typeof DeveloperWalletRoute
  DeveloperIndexRoute: typeof DeveloperIndexRoute
}

const DeveloperRouteChildren: DeveloperRouteChildren = {
  DeveloperContractsRoute: DeveloperContractsRoute,
  DeveloperJobsRoute: DeveloperJobsRoute,
  DeveloperJobsForYouRoute: DeveloperJobsForYouRoute,
  DeveloperMessagesRoute: DeveloperMessagesRoute,
  DeveloperPaymentMethodsRoute: DeveloperPaymentMethodsRoute,
  DeveloperProfileRoute: DeveloperProfileRoute,
  DeveloperProposalsRoute: DeveloperProposalsRoute,
  DeveloperSettingsRoute: DeveloperSettingsRoute,
  DeveloperWalletRoute: DeveloperWalletRoute,
  DeveloperIndexRoute: DeveloperIndexRoute,
}

const DeveloperRouteWithChildren = DeveloperRoute._addFileChildren(
  DeveloperRouteChildren,
)

interface JobsRouteChildren {
  JobsJobIdRoute: typeof JobsJobIdRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdRoute: JobsJobIdRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientRoute: ClientRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DeveloperRoute: DeveloperRouteWithChildren,
  JobsRoute: JobsRouteWithChildren,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  WalletRoute: WalletRoute,
  DebugAuthStateRoute: DebugAuthStateRoute,
  DebugImpersonateRoute: DebugImpersonateRoute,
  TalentUserIdRoute: TalentUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
