/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClientRouteImport } from './routes/client'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeveloperIndexRouteImport } from './routes/developer.index'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as TalentUserIdRouteImport } from './routes/talent.$userId'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as DeveloperProposalsRouteImport } from './routes/developer.proposals'
import { Route as DeveloperActiveJobsRouteImport } from './routes/developer.active-jobs'
import { Route as DebugImpersonateRouteImport } from './routes/debug/impersonate'
import { Route as DebugAuthStateRouteImport } from './routes/debug/auth-state'
import { Route as ClientTalentRouteImport } from './routes/client.talent'
import { Route as ClientPostJobRouteImport } from './routes/client.post-job'
import { Route as ClientPayoutsRouteImport } from './routes/client.payouts'
import { Route as ClientActiveContractsRouteImport } from './routes/client.active-contracts'
import { Route as ApiInngestRouteImport } from './routes/api/inngest'
import { Route as ClientProjectsJobIdRouteImport } from './routes/client.projects.$jobId'
import { Route as ClientDisputesNewRouteImport } from './routes/client.disputes.new'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperIndexRoute = DeveloperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeveloperRoute,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const TalentUserIdRoute = TalentUserIdRouteImport.update({
  id: '/talent/$userId',
  path: '/talent/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => JobsRoute,
} as any)
const DeveloperProposalsRoute = DeveloperProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => DeveloperRoute,
} as any)
const DeveloperActiveJobsRoute = DeveloperActiveJobsRouteImport.update({
  id: '/active-jobs',
  path: '/active-jobs',
  getParentRoute: () => DeveloperRoute,
} as any)
const DebugImpersonateRoute = DebugImpersonateRouteImport.update({
  id: '/debug/impersonate',
  path: '/debug/impersonate',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugAuthStateRoute = DebugAuthStateRouteImport.update({
  id: '/debug/auth-state',
  path: '/debug/auth-state',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientTalentRoute = ClientTalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => ClientRoute,
} as any)
const ClientPostJobRoute = ClientPostJobRouteImport.update({
  id: '/post-job',
  path: '/post-job',
  getParentRoute: () => ClientRoute,
} as any)
const ClientPayoutsRoute = ClientPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => ClientRoute,
} as any)
const ClientActiveContractsRoute = ClientActiveContractsRouteImport.update({
  id: '/active-contracts',
  path: '/active-contracts',
  getParentRoute: () => ClientRoute,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientProjectsJobIdRoute = ClientProjectsJobIdRouteImport.update({
  id: '/projects/$jobId',
  path: '/projects/$jobId',
  getParentRoute: () => ClientRoute,
} as any)
const ClientDisputesNewRoute = ClientDisputesNewRouteImport.update({
  id: '/disputes/new',
  path: '/disputes/new',
  getParentRoute: () => ClientRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client': typeof ClientRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/developer': typeof DeveloperRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/wallet': typeof WalletRoute
  '/api/inngest': typeof ApiInngestRoute
  '/client/active-contracts': typeof ClientActiveContractsRoute
  '/client/payouts': typeof ClientPayoutsRoute
  '/client/post-job': typeof ClientPostJobRoute
  '/client/talent': typeof ClientTalentRoute
  '/debug/auth-state': typeof DebugAuthStateRoute
  '/debug/impersonate': typeof DebugImpersonateRoute
  '/developer/active-jobs': typeof DeveloperActiveJobsRoute
  '/developer/proposals': typeof DeveloperProposalsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/talent/$userId': typeof TalentUserIdRoute
  '/client/': typeof ClientIndexRoute
  '/developer/': typeof DeveloperIndexRoute
  '/client/disputes/new': typeof ClientDisputesNewRoute
  '/client/projects/$jobId': typeof ClientProjectsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/wallet': typeof WalletRoute
  '/api/inngest': typeof ApiInngestRoute
  '/client/active-contracts': typeof ClientActiveContractsRoute
  '/client/payouts': typeof ClientPayoutsRoute
  '/client/post-job': typeof ClientPostJobRoute
  '/client/talent': typeof ClientTalentRoute
  '/debug/auth-state': typeof DebugAuthStateRoute
  '/debug/impersonate': typeof DebugImpersonateRoute
  '/developer/active-jobs': typeof DeveloperActiveJobsRoute
  '/developer/proposals': typeof DeveloperProposalsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/talent/$userId': typeof TalentUserIdRoute
  '/client': typeof ClientIndexRoute
  '/developer': typeof DeveloperIndexRoute
  '/client/disputes/new': typeof ClientDisputesNewRoute
  '/client/projects/$jobId': typeof ClientProjectsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/client': typeof ClientRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/developer': typeof DeveloperRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/wallet': typeof WalletRoute
  '/api/inngest': typeof ApiInngestRoute
  '/client/active-contracts': typeof ClientActiveContractsRoute
  '/client/payouts': typeof ClientPayoutsRoute
  '/client/post-job': typeof ClientPostJobRoute
  '/client/talent': typeof ClientTalentRoute
  '/debug/auth-state': typeof DebugAuthStateRoute
  '/debug/impersonate': typeof DebugImpersonateRoute
  '/developer/active-jobs': typeof DeveloperActiveJobsRoute
  '/developer/proposals': typeof DeveloperProposalsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/talent/$userId': typeof TalentUserIdRoute
  '/client/': typeof ClientIndexRoute
  '/developer/': typeof DeveloperIndexRoute
  '/client/disputes/new': typeof ClientDisputesNewRoute
  '/client/projects/$jobId': typeof ClientProjectsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client'
    | '/dashboard'
    | '/developer'
    | '/jobs'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/signup'
    | '/wallet'
    | '/api/inngest'
    | '/client/active-contracts'
    | '/client/payouts'
    | '/client/post-job'
    | '/client/talent'
    | '/debug/auth-state'
    | '/debug/impersonate'
    | '/developer/active-jobs'
    | '/developer/proposals'
    | '/jobs/$jobId'
    | '/talent/$userId'
    | '/client/'
    | '/developer/'
    | '/client/disputes/new'
    | '/client/projects/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/jobs'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/signup'
    | '/wallet'
    | '/api/inngest'
    | '/client/active-contracts'
    | '/client/payouts'
    | '/client/post-job'
    | '/client/talent'
    | '/debug/auth-state'
    | '/debug/impersonate'
    | '/developer/active-jobs'
    | '/developer/proposals'
    | '/jobs/$jobId'
    | '/talent/$userId'
    | '/client'
    | '/developer'
    | '/client/disputes/new'
    | '/client/projects/$jobId'
  id:
    | '__root__'
    | '/'
    | '/client'
    | '/dashboard'
    | '/developer'
    | '/jobs'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/signup'
    | '/wallet'
    | '/api/inngest'
    | '/client/active-contracts'
    | '/client/payouts'
    | '/client/post-job'
    | '/client/talent'
    | '/debug/auth-state'
    | '/debug/impersonate'
    | '/developer/active-jobs'
    | '/developer/proposals'
    | '/jobs/$jobId'
    | '/talent/$userId'
    | '/client/'
    | '/developer/'
    | '/client/disputes/new'
    | '/client/projects/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientRoute: typeof ClientRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DeveloperRoute: typeof DeveloperRouteWithChildren
  JobsRoute: typeof JobsRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  WalletRoute: typeof WalletRoute
  ApiInngestRoute: typeof ApiInngestRoute
  DebugAuthStateRoute: typeof DebugAuthStateRoute
  DebugImpersonateRoute: typeof DebugImpersonateRoute
  TalentUserIdRoute: typeof TalentUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/': {
      id: '/developer/'
      path: '/'
      fullPath: '/developer/'
      preLoaderRoute: typeof DeveloperIndexRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/talent/$userId': {
      id: '/talent/$userId'
      path: '/talent/$userId'
      fullPath: '/talent/$userId'
      preLoaderRoute: typeof TalentUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/developer/proposals': {
      id: '/developer/proposals'
      path: '/proposals'
      fullPath: '/developer/proposals'
      preLoaderRoute: typeof DeveloperProposalsRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/developer/active-jobs': {
      id: '/developer/active-jobs'
      path: '/active-jobs'
      fullPath: '/developer/active-jobs'
      preLoaderRoute: typeof DeveloperActiveJobsRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/debug/impersonate': {
      id: '/debug/impersonate'
      path: '/debug/impersonate'
      fullPath: '/debug/impersonate'
      preLoaderRoute: typeof DebugImpersonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/auth-state': {
      id: '/debug/auth-state'
      path: '/debug/auth-state'
      fullPath: '/debug/auth-state'
      preLoaderRoute: typeof DebugAuthStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/talent': {
      id: '/client/talent'
      path: '/talent'
      fullPath: '/client/talent'
      preLoaderRoute: typeof ClientTalentRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/post-job': {
      id: '/client/post-job'
      path: '/post-job'
      fullPath: '/client/post-job'
      preLoaderRoute: typeof ClientPostJobRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/payouts': {
      id: '/client/payouts'
      path: '/payouts'
      fullPath: '/client/payouts'
      preLoaderRoute: typeof ClientPayoutsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/active-contracts': {
      id: '/client/active-contracts'
      path: '/active-contracts'
      fullPath: '/client/active-contracts'
      preLoaderRoute: typeof ClientActiveContractsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/projects/$jobId': {
      id: '/client/projects/$jobId'
      path: '/projects/$jobId'
      fullPath: '/client/projects/$jobId'
      preLoaderRoute: typeof ClientProjectsJobIdRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/disputes/new': {
      id: '/client/disputes/new'
      path: '/disputes/new'
      fullPath: '/client/disputes/new'
      preLoaderRoute: typeof ClientDisputesNewRouteImport
      parentRoute: typeof ClientRoute
    }
  }
}

interface ClientRouteChildren {
  ClientActiveContractsRoute: typeof ClientActiveContractsRoute
  ClientPayoutsRoute: typeof ClientPayoutsRoute
  ClientPostJobRoute: typeof ClientPostJobRoute
  ClientTalentRoute: typeof ClientTalentRoute
  ClientIndexRoute: typeof ClientIndexRoute
  ClientDisputesNewRoute: typeof ClientDisputesNewRoute
  ClientProjectsJobIdRoute: typeof ClientProjectsJobIdRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientActiveContractsRoute: ClientActiveContractsRoute,
  ClientPayoutsRoute: ClientPayoutsRoute,
  ClientPostJobRoute: ClientPostJobRoute,
  ClientTalentRoute: ClientTalentRoute,
  ClientIndexRoute: ClientIndexRoute,
  ClientDisputesNewRoute: ClientDisputesNewRoute,
  ClientProjectsJobIdRoute: ClientProjectsJobIdRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface DeveloperRouteChildren {
  DeveloperActiveJobsRoute: typeof DeveloperActiveJobsRoute
  DeveloperProposalsRoute: typeof DeveloperProposalsRoute
  DeveloperIndexRoute: typeof DeveloperIndexRoute
}

const DeveloperRouteChildren: DeveloperRouteChildren = {
  DeveloperActiveJobsRoute: DeveloperActiveJobsRoute,
  DeveloperProposalsRoute: DeveloperProposalsRoute,
  DeveloperIndexRoute: DeveloperIndexRoute,
}

const DeveloperRouteWithChildren = DeveloperRoute._addFileChildren(
  DeveloperRouteChildren,
)

interface JobsRouteChildren {
  JobsJobIdRoute: typeof JobsJobIdRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdRoute: JobsJobIdRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientRoute: ClientRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DeveloperRoute: DeveloperRouteWithChildren,
  JobsRoute: JobsRouteWithChildren,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  WalletRoute: WalletRoute,
  ApiInngestRoute: ApiInngestRoute,
  DebugAuthStateRoute: DebugAuthStateRoute,
  DebugImpersonateRoute: DebugImpersonateRoute,
  TalentUserIdRoute: TalentUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
