/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardWalletRouteImport } from './routes/dashboard.wallet'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardProposalsRouteImport } from './routes/dashboard.proposals'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPaymentMethodsRouteImport } from './routes/dashboard.payment-methods'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardJobsForYouRouteImport } from './routes/dashboard.jobs-for-you'
import { Route as DashboardJobsRouteImport } from './routes/dashboard.jobs'
import { Route as DashboardContractsRouteImport } from './routes/dashboard.contracts'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWalletRoute = DashboardWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProposalsRoute = DashboardProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentMethodsRoute = DashboardPaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsForYouRoute = DashboardJobsForYouRouteImport.update({
  id: '/jobs-for-you',
  path: '/jobs-for-you',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContractsRoute = DashboardContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/contracts': typeof DashboardContractsRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/jobs-for-you': typeof DashboardJobsForYouRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/payment-methods': typeof DashboardPaymentMethodsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/proposals': typeof DashboardProposalsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/contracts': typeof DashboardContractsRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/jobs-for-you': typeof DashboardJobsForYouRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/payment-methods': typeof DashboardPaymentMethodsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/proposals': typeof DashboardProposalsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/contracts': typeof DashboardContractsRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/jobs-for-you': typeof DashboardJobsForYouRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/payment-methods': typeof DashboardPaymentMethodsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/proposals': typeof DashboardProposalsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/contracts'
    | '/dashboard/jobs'
    | '/dashboard/jobs-for-you'
    | '/dashboard/messages'
    | '/dashboard/payment-methods'
    | '/dashboard/profile'
    | '/dashboard/proposals'
    | '/dashboard/settings'
    | '/dashboard/wallet'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/contracts'
    | '/dashboard/jobs'
    | '/dashboard/jobs-for-you'
    | '/dashboard/messages'
    | '/dashboard/payment-methods'
    | '/dashboard/profile'
    | '/dashboard/proposals'
    | '/dashboard/settings'
    | '/dashboard/wallet'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/contracts'
    | '/dashboard/jobs'
    | '/dashboard/jobs-for-you'
    | '/dashboard/messages'
    | '/dashboard/payment-methods'
    | '/dashboard/profile'
    | '/dashboard/proposals'
    | '/dashboard/settings'
    | '/dashboard/wallet'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/wallet': {
      id: '/dashboard/wallet'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof DashboardWalletRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/proposals': {
      id: '/dashboard/proposals'
      path: '/proposals'
      fullPath: '/dashboard/proposals'
      preLoaderRoute: typeof DashboardProposalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payment-methods': {
      id: '/dashboard/payment-methods'
      path: '/payment-methods'
      fullPath: '/dashboard/payment-methods'
      preLoaderRoute: typeof DashboardPaymentMethodsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jobs-for-you': {
      id: '/dashboard/jobs-for-you'
      path: '/jobs-for-you'
      fullPath: '/dashboard/jobs-for-you'
      preLoaderRoute: typeof DashboardJobsForYouRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jobs': {
      id: '/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contracts': {
      id: '/dashboard/contracts'
      path: '/contracts'
      fullPath: '/dashboard/contracts'
      preLoaderRoute: typeof DashboardContractsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardContractsRoute: typeof DashboardContractsRoute
  DashboardJobsRoute: typeof DashboardJobsRoute
  DashboardJobsForYouRoute: typeof DashboardJobsForYouRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardPaymentMethodsRoute: typeof DashboardPaymentMethodsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardProposalsRoute: typeof DashboardProposalsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardWalletRoute: typeof DashboardWalletRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardContractsRoute: DashboardContractsRoute,
  DashboardJobsRoute: DashboardJobsRoute,
  DashboardJobsForYouRoute: DashboardJobsForYouRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardPaymentMethodsRoute: DashboardPaymentMethodsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardProposalsRoute: DashboardProposalsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardWalletRoute: DashboardWalletRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
